# The URL the site will be built for
base_url = "https://bonfari.netlify.app/"
generate_rss = true
compile_sass = true

title = "Bonfari"
description = "De website van Stichting Bonfari"
highlight_code = true

taxonomies = [
    {name = "categorie", rss = true, paginate_by=5},
    {name = "projecten", rss = true, paginate_by=5},
    {name = "functies", rss = true, paginate_by=5}
]

[extra]
author = "Bonfari"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/over", name = "Over"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
