# The URL the site will be built for
base_url = "https://bonfari.netlify.app"
generate_rss = true
compile_sass = true

title = "Stichting Bonfari"
description = "Value-based volunteering"
highlight_code = true

taxonomies = [
    {name = "tags", rss = false, paginate_by=5},
    {name = "type", rss = false, paginate_by=5},
    {name = "project", rss = false, paginate_by=5},
]

[extra]
year = "2020"
author = "Bonfari"
clean_blog_menu = [
    {url = "$BASE_URL/vrijwilligers", name = "Vrijwilligers"},
    {url = "$BASE_URL/doelvisie", name = "Doel & Visie"},
    {url = "$BASE_URL/projecten", name = "Projecten"},
    {url = "$BASE_URL/type/financien", name = "Financiën"},
    {url = "$BASE_URL/over", name = "Over"},
    {url = "$BASE_URL/blog", name = "Blog"},
]

clean_blog_social = [
    {url = "https://www.linkedin.com/company/stichting-bonfari/", icon="fab fa-linkedin"},
    {url = "https://twitter.com/St_Bonfari", icon="fab fa-twitter"},
    {url = "https://www.facebook.com/StichtingBonfari/", icon="fab fa-facebook"},
    {url = "https://www.instagram.com/st.bonfari/?hl=en", icon="fab fa-instagram"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
