backend:
    name: git-gateway

# global
media_library:
  name: 
  config:
    cloud_name: bonfari
    api_key: 994249357162695
  output_filename_only: true
  config:
    default_transformations:
      - - fetch_format: auto
        #   width: 160
          quality: auto
          crop: fill

collections:
    - name: "posts" # Used in routes, e.g., /admin/collections/blog
      format: "toml-frontmatter"
      label: "Posts" # Used in the UI
      folder: "content/blog" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "date" }
          - {
                label: "Taxonomies",
                name: "taxonomies",
                widget: "object",
                fields:
                    [
                        { label: "tags", name: "tags", widget: "list" },
                        { label: "Project", name: "projecten", widget: "list" },
                        { label: "Functies", name: "functies", widget: "list" },
                    ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
