backend:
    name: git-gateway

# global
media_library:
    name: cloudinary
    config:
        cloud_name: bonfari
        api_key: 994249357162695
        default_transformations:
        - - fetch_format: auto
            width: 768
            quality: auto
            crop: fill

collections:
    - name: "blogs" # Used in routes, e.g., /admin/collections/blog
      identifier_field: "{{title}}-{{taxonomies.tags}}"
      format: "toml-frontmatter"
      label: "blogs" # Used in the UI
      folder: "content/blog" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "date" }
          - { label: "Draft", name: "draft",  widget: "boolean", default: true}
          - {
                label: "Taxonomies",
                name: "taxonomies",
                widget: "object",
                fields:
                    [
                        { label: "type", name: "type", widget: "select", multiple: true, min: 1, max: 3, options: ["Blog", "Financiën", "Project"], default: ["Blog"]},
                        { label: "project", name: "project", widget: "relation", collection: "projecten", searchFields: ["title"], valueField: "title", required: false},
                        { label: "tags", name: "tags", widget: "list"},
                    ],
            }
          - {
                label: "Extra",
                name: "extra",
                fields:
                    [
                        { label: "author", name: "author", valueType: "string"},
                    ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: "projecten" # Used in routes, e.g., /admin/collections/blog
      format: "toml-frontmatter"
      label: "projecten" # Used in the UI
      folder: "content/projecten" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "date" }
          - { label: "Draft", name: "draft", widget: "boolean", default: true}
          - {
                label: "Extra",
                name: "extra",
                fields:
                    [
                        { label: "col", name: "col", widget: "hidden", valueType: "int", default: 4},
                        { label: "author", name: "author", valueType: "string"},
                    ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
